//
// Created by Cameron on 25/04/2023.
//

#ifndef SFMLGAME_SCENEENUMS_H
#define SFMLGAME_SCENEENUMS_H

enum class Scenes {SPLASH, MAIN_MENU, SERVER, CLIENT, ESCAPEE, GUARD};

#endif // SFMLGAME_SCENEENUMS_H
